export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const ADD_APPLICATION = "ADD_APPLICATION";
export const DATA_LOADED = "DATA_LOADED";
export const DELETE_APPLICATION = "DELETE_APPLICATION";